### ISSUE TITLE
poky: subtree update failing to build webui-vue recipe

### ISSUE THREAD

**Issue by geissonator** [openbmc/webui-vue#37]
I brought in an upstream poky update over the weekend and we're hitting a compile failure with vue.

https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/36615/ is the commit.

```
[955A[J[1;31mERROR[0m: [31mLogfile of failure stored in: /var/lib/jenkins-slave/workspace/ci-openbmc/distro/ubuntu/label/docker-builder/target/witherspoon-tacoma/build/work/all-openbmc-linux/webui-vue/1.0+gitAUTOINC+0214fedb49-r1/temp/log.do_compile.19224[0m
Log data follows:
| DEBUG: Executing shell function do_compile
| TypeError: Cannot convert name to ASCII
|     at Url.parse (url.js:389:23)
|     at Object.urlParse [as parse] (url.js:154:13)
|     at Object.validateUrl [as validate] (/var/lib/jenkins-slave/workspace/ci-openbmc/distro/ubuntu/label/docker-builder/target/witherspoon-tacoma/build/work/all-openbmc-linux/webui-vue/1.0+gitAUTOINC+0214fedb49-r1/recipe-sysroot-native/usr/lib/node_modules/npm/node_modules/nopt/lib/nopt.js:177:13)
|     at validate (/var/lib/jenkins-slave/workspace/ci-openbmc/distro/ubuntu/label/docker-builder/target/witherspoon-tacoma/build/work/all-openbmc-linux/webui-vue/1.0+gitAUTOINC+0214fedb49-r1/recipe-sysroot-native/usr/lib/node_modules/npm/node_modules/nopt/lib/nopt.js:226:24)
|     at validate (/var/lib/jenkins-slave/workspace/ci-openbmc/distro/ubuntu/label/docker-builder/target/witherspoon-tacoma/build/work/all-openbmc-linux/webui-vue/1.0+gitAUTOINC+0214fedb49-r1/recipe-sysroot-native/usr/lib/node_modules/npm/node_modules/nopt/lib/nopt.js:192:11)
|     at /var/lib/jenkins-slave/workspace/ci-openbmc/distro/ubuntu/label/docker-builder/target/witherspoon-tacoma/build/work/all-openbmc-linux/webui-vue/1.0+gitAUTOINC+0214fedb49-r1/recipe-sysroot-native/usr/lib/node_modules/npm/node_modules/nopt/lib/nopt.js:104:12
|     at Array.map (<anonymous>)
|     at /var/lib/jenkins-slave/workspace/ci-openbmc/distro/ubuntu/label/docker-builder/target/witherspoon-tacoma/build/work/all-openbmc-linux/webui-vue/1.0+gitAUTOINC+0214fedb49-r1/recipe-sysroot-native/usr/lib/node_modules/npm/node_modules/nopt/lib/nopt.js:70:15
|     at Array.forEach (<anonymous>)
|     at Function.clean (/var/lib/jenkins-slave/workspace/ci-openbmc/distro/ubuntu/label/docker-builder/target/witherspoon-tacoma/build/work/all-openbmc-linux/webui-vue/1.0+gitAUTOINC+0214fedb49-r1/recipe-sysroot-native/usr/lib/node_modules/npm/node_modules/nopt/lib/nopt.js:58:21)
| /var/lib/jenkins-slave/workspace/ci-openbmc/distro/ubuntu/label/docker-builder/target/witherspoon-tacoma/build/work/all-openbmc-linux/webui-vue/1.0+gitAUTOINC+0214fedb49-r1/recipe-sysroot-native/usr/lib/node_modules/npm/lib/npm.js:59
|       throw new Error('npm.load() required')
|       ^
| 
| Error: npm.load() required
|     at Object.get (/var/lib/jenkins-slave/workspace/ci-openbmc/distro/ubuntu/label/docker-builder/target/witherspoon-tacoma/build/work/all-openbmc-linux/webui-vue/1.0+gitAUTOINC+0214fedb49-r1/recipe-sysroot-native/usr/lib/node_modules/npm/lib/npm.js:59:13)
|     at process.errorHandler (/var/lib/jenkins-slave/workspace/ci-openbmc/distro/ubuntu/label/docker-builder/target/witherspoon-tacoma/build/work/all-openbmc-linux/webui-vue/1.0+gitAUTOINC+0214fedb49-r1/recipe-sysroot-native/usr/lib/node_modules/npm/lib/utils/error-handler.js:208:32)
|     at process.emit (events.js:315:20)
|     at process._fatalException (internal/process/execution.js:165:25)
| WARNING: exit code 7 from a shell command.
| ERROR: Execution of '/var/lib/jenkins-slave/workspace/ci-openbmc/distro/ubuntu/label/docker-builder/target/witherspoon-tacoma/build/work/all-openbmc-linux/webui-vue/1.0+gitAUTOINC+0214fedb49-r1/temp/run.do_compile.19224' failed with exit code 7:
| TypeError: Cannot convert name to ASCII
|     at Url.parse (url.js:389:23)
|     at Object.urlParse [as parse] (url.js:154:13)
|     at Object.validateUrl [as validate] (/var/lib/jenkins-slave/workspace/ci-openbmc/distro/ubuntu/label/docker-builder/target/witherspoon-tacoma/build/work/all-openbmc-linux/webui-vue/1.0+gitAUTOINC+0214fedb49-r1/recipe-sysroot-native/usr/lib/node_modules/npm/node_modules/nopt/lib/nopt.js:177:13)
|     at validate (/var/lib/jenkins-slave/workspace/ci-openbmc/distro/ubuntu/label/docker-builder/target/witherspoon-tacoma/build/work/all-openbmc-linux/webui-vue/1.0+gitAUTOINC+0214fedb49-r1/recipe-sysroot-native/usr/lib/node_modules/npm/node_modules/nopt/lib/nopt.js:226:24)
|     at validate (/var/lib/jenkins-slave/workspace/ci-openbmc/distro/ubuntu/label/docker-builder/target/witherspoon-tacoma/build/work/all-openbmc-linux/webui-vue/1.0+gitAUTOINC+0214fedb49-r1/recipe-sysroot-native/usr/lib/node_modules/npm/node_modules/nopt/lib/nopt.js:192:11)
|     at /var/lib/jenkins-slave/workspace/ci-openbmc/distro/ubuntu/label/docker-builder/target/witherspoon-tacoma/build/work/all-openbmc-linux/webui-vue/1.0+gitAUTOINC+0214fedb49-r1/recipe-sysroot-native/usr/lib/node_modules/npm/node_modules/nopt/lib/nopt.js:104:12
|     at Array.map (<anonymous>)
|     at /var/lib/jenkins-slave/workspace/ci-openbmc/distro/ubuntu/label/docker-builder/target/witherspoon-tacoma/build/work/all-openbmc-linux/webui-vue/1.0+gitAUTOINC+0214fedb49-r1/recipe-sysroot-native/usr/lib/node_modules/npm/node_modules/nopt/lib/nopt.js:70:15
|     at Array.forEach (<anonymous>)
|     at Function.clean (/var/lib/jenkins-slave/workspace/ci-openbmc/distro/ubuntu/label/docker-builder/target/witherspoon-tacoma/build/work/all-openbmc-linux/webui-vue/1.0+gitAUTOINC+0214fedb49-r1/recipe-sysroot-native/usr/lib/node_modules/npm/node_modules/nopt/lib/nopt.js:58:21)
| /var/lib/jenkins-slave/workspace/ci-openbmc/distro/ubuntu/label/docker-builder/target/witherspoon-tacoma/build/work/all-openbmc-linux/webui-vue/1.0+gitAUTOINC+0214fedb49-r1/recipe-sysroot-native/usr/lib/node_modules/npm/lib/npm.js:59
|       throw new Error('npm.load() required')
|       ^
| 
| Error: npm.load() required
|     at Object.get (/var/lib/jenkins-slave/workspace/ci-openbmc/distro/ubuntu/label/docker-builder/target/witherspoon-tacoma/build/work/all-openbmc-linux/webui-vue/1.0+gitAUTOINC+0214fedb49-r1/recipe-sysroot-native/usr/lib/node_modules/npm/lib/npm.js:59:13)
|     at process.errorHandler (/var/lib/jenkins-slave/workspace/ci-openbmc/distro/ubuntu/label/docker-builder/target/witherspoon-tacoma/build/work/all-openbmc-linux/webui-vue/1.0+gitAUTOINC+0214fedb49-r1/recipe-sysroot-native/usr/lib/node_modules/npm/lib/utils/error-handler.js:208:32)
|     at process.emit (events.js:315:20)
|     at process._fatalException (internal/process/execution.js:165:25)
| WARNING: exit code 7 from a shell command.
| 
````

**Comment by derick-montague** [comment]
I am going to to try and find some information on this, but I am not sure that is is related to Vue. This came after updating some recipe updates. This is not something that I have experienced before. If I can't find a solution, I will reach out to the community on IRC. @gtmills would be helpful and I will let him know when he is available if we haven't found a solution.

**Comment by gtmills** [comment]
This looks to be related to https://github.com/openbmc/openbmc/issues/3665

**Comment by derick-montague** [comment]
Can we close this issue @gtmills?

**Comment by gtmills** [comment]
No, still a problem

**Comment by derick-montague** [comment]
I guess thought it was not an issue we could resolve in this repo.

**Comment by gtmills** [comment]
Rebased the bump: https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/36615/ and for some reason passed on witherspoon-tacoma (webui-vue)
The commit on top, https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/37032/  failed on witherspoon (phosphor-webui)

The fail was on builder2. Passes were on builder1, builder4, builder5

**Comment by derick-montague** [comment]
Looks like the internal tracking story was closed?

**Comment by gtmills** [comment]
I can still recreate locally with a long path; 
I don't think this is truly fixed when though I see https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/36615/ and https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/37032/  passes now for these systems. 
I think npm cache issue or npm cache now fixes. I vote we hold off on closing

**Comment by gtmills** [comment]
Recreated today on builder2 
https://jenkins.openbmc.org/job/ci-openbmc/764/ and https://jenkins.openbmc.org/job/ci-openbmc/765/

**Comment by gtmills** [comment]
Haven't seen this for a long time. I am closing. 
@geissonator Let me know if you object and we can reopen
