### ISSUE TITLE
Can not login webui-vue

### ISSUE THREAD

**Issue by LW-Ho** [openbmc/webui-vue#50]
**Describe the bug**
I can running OpenBMC webui-vue, and then press root and 0penBmc  but always show alert "Invalid username or password"

**Screenshots**
https://imgur.com/Jx4S63S

**Additional context**

TypeError: Cannot read property 'split' of null
    at required (/home/XXXX/Documents/webui-vue-2/node_modules/requires-port/index.js:13:23)
    at Object.common.setupOutgoing (/home/XXXX/Documents/webui-vue-2/node_modules/http-proxy/lib/http-proxy/common.js:101:7)
    at Array.stream (/home/XXXX/Documents/webui-vue-2/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:127:14)
    at ProxyServer.<anonymous> (/home/XXXX/Documents/webui-vue-2/node_modules/http-proxy/lib/http-proxy/index.js:81:21)
    at middleware (/home/XXXX/Documents/webui-vue-2/node_modules/http-proxy-middleware/lib/index.js:46:13)
    at handle (/home/XXXX/Documents/webui-vue-2/node_modules/webpack-dev-server/lib/Server.js:322:18)
    at /home/XXXX/Documents/webui-vue-2/node_modules/webpack-dev-server/lib/Server.js:330:47
    at Layer.handle_error (/home/XXXX/Documents/webui-vue-2/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/XXXX/Documents/webui-vue-2/node_modules/express/lib/router/index.js:315:13)
    at /home/XXXX/Documents/webui-vue-2/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/XXXX/Documents/webui-vue-2/node_modules/express/lib/router/index.js:335:12)
    at next (/home/XXXX/Documents/webui-vue-2/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle [as handle_request] (/home/XXXX/Documents/webui-vue-2/node_modules/express/lib/router/layer.js:97:5)
    at trim_prefix (/home/XXXX/Documents/webui-vue-2/node_modules/express/lib/router/index.js:317:13)
    at /home/XXXX/Documents/webui-vue-2/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/XXXX/Documents/webui-vue-2/node_modules/express/lib/router/index.js:335:12)

Thanks a lot.

**Comment by yoshiemuranaka** [comment]
You may be missing the protocol in the .env file `BASE_URL` variable `https://<ip>`

**Comment by LW-Ho** [comment]
> You may be missing the protocol in the .env file `BASE_URL` variable `https://<ip>`

Okay, i found the problem
I referred to CONTRIBUTING.md
- BASE_URL="https://<BMC IP address or FQDN>"`
at last BASE_URL this line have ` , i remove this , the error not show again.

There is a ` in the last line. After I removed it, the error message no longer appeared
But i still can't log in, and server not output any log.

Thanks a lot.

**Comment by seirespcp** [comment]
Your log says home. Are you running webui-vue on your local machine?
If so, this could be a cross site security issue
See https://github.com/openbmc/phosphor-webui#logging-in

**Comment by derick-montague** [comment]
I am not sure the phosphor-webui guidance will be helpful as the webui-vue has been easier to run locally. @LW-Ho are there any errors on the browser's dev tools console?

**Comment by LW-Ho** [comment]
Sorry, I confuse the intention of this front-end and mistakenly think that BMC Host is the IP of the frontend itself. After I realize that BMC is my hardware device, I can log in successfully by opening the BMC device.

**Comment by derick-montague** [comment]
Glad the issue is resolved and please share any feedback you have about the UI. Thanks!
